"""add category to Dish

Revision ID: 0ac99f369cd6
Revises: 8d6cd7120b95
Create Date: 2025-07-29 12:48:20.309602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac99f369cd6'
down_revision = '8d6cd7120b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
